name: CI Pipeline

# This pipeline is executed every time a push is made to main or a pull request is made
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Set up environment variables
      run: |
        echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> $GITHUB_ENV
        echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
        echo "MONGODB_CLUSTER=${{ secrets.MONGODB_CLUSTER }}" >> $GITHUB_ENV

    # Set up PYTHONPATH to ensure app.py can be found
    - name: Set up PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    # Run tests for routes
    - name: Run tests for routes
      run: |
        pytest tests/test_routes.py  

    # Run tests for database connection
    - name: Run tests for database connection
      run: |
        pytest tests/test_database.py 

    # Run tests for database write
    - name: Run tests for database write
      run: |
        pytest tests/test_database_write.py
